#!/usr/bin/env python3
"""
Recreate the tasks/ folder with all 28 benchmark task files.
Run this inside your project folder (where runner.py lives):

    python3 create_tasks.py

It creates tasks/coding, tasks/reasoning, tasks/text, tasks/structured
and writes all 28 .md prompts into them.
"""
from pathlib import Path

TASKS = {
    'coding/01_fizzbuzz.md': 'Write a Python function `solve(n)` that returns a list of strings for numbers 1..n.\nRules: multiples of 3 -> "fizz", multiples of 5 -> "buzz", multiples of 7 -> "bang".\nCombine in that order (e.g. 105 -> "fizzbuzzbang"). Other numbers -> the number as a string.\nReturn ONLY the function in a single python code block, no explanation.\n',
    'coding/02_palindrome.md': 'Write a Python function `is_palindrome(s)` that returns True if the string is a palindrome, ignoring case, spaces, and punctuation. Empty string returns True.\nExamples: "A man, a plan, a canal: Panama" -> True; "race a car" -> False.\nReturn ONLY the function in a single python code block, no explanation.\n',
    'coding/03_bug_fix.md': 'This Python function should return the second largest UNIQUE value in a list, or None if it does not exist. It has bugs. Return the corrected function in a single python code block named `second_largest`, no explanation.\n\ndef second_largest(nums):\n    nums = sorted(nums)\n    return nums[-2]\n',
    'coding/04_sql.md': 'Given tables:\n  orders(id, customer_id, total_cents, created_at)\n  customers(id, name, country)\nWrite ONE PostgreSQL query that returns, for each country, the number of customers who placed at least one order in 2025 and their total revenue in euros (total_cents/100), ordered by revenue descending. Return ONLY the SQL in a single code block.\n',
    'coding/05_lru_cache.md': 'Implement a Python class `LRUCache` with a fixed capacity set in the constructor: `LRUCache(capacity)`.\nMethods: `get(key)` returns the value or -1 if absent; `put(key, value)` inserts/updates and evicts the least-recently-used item when over capacity. Both must be O(1) average. Using collections.OrderedDict is allowed.\nReturn ONLY the class in a single python code block, no explanation.\n',
    'coding/06_intervals.md': 'Write a Python function `merge(intervals)` that takes a list of [start, end] pairs and returns the list of merged, non-overlapping intervals sorted by start. Touching intervals like [1,2] and [2,3] merge into [1,3].\nExample: [[1,3],[2,6],[8,10],[15,18]] -> [[1,6],[8,10],[15,18]].\nReturn ONLY the function in a single python code block, no explanation.\n',
    'coding/07_parens.md': 'Write a Python function `generate(n)` that returns a list of all combinations of n pairs of well-formed parentheses, in any order.\nExample: generate(3) -> ["((()))","(()())","(())()","()(())","()()()"] (order does not matter).\nReturn ONLY the function in a single python code block, no explanation.\n',
    'reasoning/01_water_jugs.md': 'You have a 3-litre jug and a 5-litre jug and unlimited water. Describe the exact sequence of steps to measure out exactly 4 litres. List each step on its own line.\n',
    'reasoning/02_boxes.md': 'Three boxes are labeled "Apples", "Oranges", and "Apples & Oranges". Every label is wrong. You may draw ONE fruit from ONE box (without looking inside). Which box do you draw from to deduce the contents of all three boxes, and what is the full reasoning? Answer concisely.\n',
    'reasoning/03_pipes.md': 'A tank is filled by pipe A in 6 hours and by pipe B in 4 hours. Pipe C empties a full tank in 12 hours. If all three are open starting from empty, how long until the tank is full? Show the calculation and give the final answer as a fraction of hours and in hours+minutes.\n',
    'reasoning/04_monty_hall.md': 'In the Monty Hall problem: 3 doors, one has a car, two have goats. You pick door 1. The host, who knows what is behind the doors, opens door 3 to reveal a goat. He offers you the chance to switch to door 2. Should you switch? State the probability of winning if you switch versus if you stay, and explain why in 2-3 sentences.\n',
    'reasoning/05_bat_ball.md': 'A bat and a ball cost 1.10 euros in total. The bat costs 1.00 euro more than the ball. How much does the ball cost? Show your reasoning and give the exact amount.\n',
    'reasoning/06_fermi.md': 'Estimate how many piano tuners work in Berlin. Do NOT look anything up. Show your chain of estimates step by step (population, pianos per person, tuning frequency, tuner workload) and give a final rough number. The reasoning matters more than the exact figure.\n',
    'reasoning/07_false_proof.md': 'The following "proof" claims that 2 = 1. Find the exact step where it goes wrong and explain why it is invalid.\n\nLet a = b.\nMultiply both sides by a:      a^2 = ab\nSubtract b^2:                   a^2 - b^2 = ab - b^2\nFactor:                         (a+b)(a-b) = b(a-b)\nDivide both sides by (a-b):     a + b = b\nSince a = b:                    2b = b\nDivide by b:                    2 = 1\n',
    'text/01_summarize.md': 'Summarize the following in exactly 3 bullet points, each under 15 words:\n\n"Ollama is a tool for running large language models locally on your own hardware. It packages model weights, configuration, and a runtime into a single application with a simple command-line interface and an HTTP API. Models are quantized to reduce memory use, which lets smaller machines run models that would otherwise require far more RAM or VRAM. Performance depends heavily on the hardware: a discrete GPU dramatically improves tokens-per-second compared to CPU-only inference, while devices like single-board computers can run only the smallest models, and slowly."\n',
    'text/02_extract_names.md': 'From the text below, extract every person name and the company they are associated with. Output as plain lines "Name - Company". If no names, output "NONE".\n\n"During the meeting, Maria Schmidt from Novoferm raised concerns about the timeline. Tom Becker, representing SIG, agreed. Later, a representative from BambooCard joined but did not give a name."\n',
    'text/03_rewrite_b1.md': 'Rewrite the paragraph below at a B1 English level: simple words, short sentences, no idioms. Keep all facts. Output only the rewritten paragraph.\n\n"Notwithstanding the considerable architectural complexity inherent in distributed microservice topologies, the engineering cohort successfully orchestrated a seamless migration, thereby mitigating latency regressions and substantially augmenting overall throughput."\n',
    'text/04_extract_contract.md': 'Extract the key terms from this contract clause as plain lines in the format "Field: value". Fields to find: Parties, Effective date, Term length, Notice period, Monthly fee.\n\n"This Agreement is entered into between Acme GmbH (\'Provider\') and Nordwind AG (\'Client\'), effective 1 March 2025. The initial term is 24 months. Either party may terminate with 60 days written notice. The Client shall pay a monthly fee of 4,500 EUR."\n',
    'text/05_contradiction.md': 'The two statements below contradict each other. Identify the specific contradiction in one sentence.\n\nStatement A: "All deliveries in the report were completed before the Friday deadline, with none arriving on the weekend."\nStatement B: "The Hamburg shipment in the same report was signed for on Saturday morning."\n',
    'text/06_no_answer.md': 'Answer the question using ONLY the text below. If the answer is not in the text, reply exactly: "Not stated in the text."\n\nText: "The Q3 report covered revenue growth in the German and Austrian markets. The team expanded to 14 people and opened a second office in Munich."\n\nQuestion: What was the company\'s total revenue in Q3?\n',
    'text/07_fix_facts.md': 'The paragraph below contains three factual errors. List each error and give the correction, one per line in the format "Error -> Correction". Do not rewrite the paragraph.\n\n"Water boils at 90 degrees Celsius at sea level. The human body has 106 bones. Light travels faster than sound, which is why we see lightning before we hear thunder. The capital of Australia is Sydney."\n',
    'structured/01_json_basic.md': 'Parse this into JSON. Output ONLY valid JSON, no markdown, no commentary.\nSchema: {"name": string, "age": number, "skills": string[], "remote": boolean}\nInput: "Artur is a 33 year old backend engineer. He knows C#, AWS and Postgres. He wants remote work."\n',
    'structured/02_classify.md': 'Classify each message as "bug", "feature_request", or "question".\nOutput ONLY a JSON array of objects {"id": number, "label": string}, no commentary.\n1: "The app crashes when I click export."\n2: "Could you add dark mode?"\n3: "How do I reset my password?"\n4: "Login button does nothing on Safari."\n',
    'structured/03_csv.md': 'Convert the following into a CSV with header "city,country,population_millions". Output ONLY the CSV, no commentary, no code block.\nTokyo is in Japan with about 37 million people. Delhi, India has roughly 33 million. Sao Paulo in Brazil has around 22 million.\n',
    'structured/04_nested_json.md': 'Produce ONLY valid JSON, no commentary, matching this structure:\n{"order_id": string, "customer": {"name": string, "vip": boolean}, "items": [{"sku": string, "qty": number}], "total": number}\nData: Order A-1007 for customer Lena Roth, who is a VIP. She ordered 2 of SKU "KB-12" and 1 of SKU "MS-04". The total is 149.97.\n',
    'structured/05_dependent_total.md': 'Produce ONLY valid JSON, no commentary:\n{"items": [{"name": string, "price": number, "qty": number, "line_total": number}], "grand_total": number}\nRules: line_total = price * qty for each item; grand_total = sum of all line_totals. Compute every number yourself.\nItems: 3 notebooks at 2.50 each; 2 pens at 1.20 each; 1 stapler at 7.99.\n',
    'structured/06_yaml.md': 'Output ONLY valid YAML, no commentary, no code fences. Represent this:\nA service named "auth-api", version 2, listening on port 8080, with two environment variables: LOG_LEVEL set to "info" and TIMEOUT set to 30. It depends on two services: "postgres" and "redis".\nUse keys: name, version, port, env (a map), depends_on (a list).\n',
    'structured/07_enum_schema.md': 'Produce ONLY valid JSON, no commentary, conforming to these constraints:\n{"username": string (lowercase, no spaces), "role": one of ["admin","editor","viewer"], "active": boolean, "login_count": integer >= 0}\nData: A user called "Sam Vega" who is an editor, currently active, has logged in 12 times. Convert the username to a valid lowercase form with no spaces.\n',
}

root = Path(__file__).parent / "tasks"
for rel, body in TASKS.items():
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body, encoding="utf-8")
    print("wrote", p)

n = len(list(root.rglob("*.md")))
print(f"\nDone. {n} task files created.")
print("Now run:  python3 selftest.py")